service: serverless-graphql
app: myapp-dev
tenant: gtwright
plugins:
  - serverless-webpack
  - serverless-offline
custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage,'dev'}
  environment: ${file(secrets.yml):${self:provider.stage}}
functions:
  graphql:
    handler: src/index.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
  playground:
    handler: src/index.handler
    events:
      - http:
          path: playground
          method: get